### ISSUE TITLE
no such table: micplot_show

### ISSUE THREAD

**Issue by diamondhoodgem** [tomgxz/Mic-Plot-Generator#8]
Hi, I have manged to install everything and run it but i am getting an issue where the web ui is saying no such table: micplot_show, if you have the table is it possible for me to have a blank one and instructions on where to put it, or if there is a file to create one but i haven't found it please do let me know

**Comment by tomgxz** [comment]
I'll add a `README.md` file to explain how to build and run the project, I'd forgotten to do one and I know why you're getting this issue.

I'll let you know when I've done it, as I'm currently away.

**Comment by tomgxz** [comment]
See [README.md](https://github.com/tomgxz/Mic-Plot-Generator/blob/master/README.md) for details of the setup. Any problems, re-open this issue :)
